### ISSUE TITLE
jupyter-o2 sporadically raises AttributeError in open_in_browser

### ISSUE THREAD

**Issue by ddingding** [AaronKollasch/jupyter-o2#3] opened 2019-05-01 15:01 UTC
Hi Aaron,
Fyi, sometimes starting jupyter-o2 results in the below error. Retrying right after resolves the issue. I remember other users have encountered this previously too.

vpn-10-1-5-125:~ davidd$ jupyter-o2
Jupyter subcommand not provided. Using default: notebook
Connect to O2 server for jupyter notebook
Enter your passphrase: 
Connecting to dd128@o2.hms.harvard.edu
Hostname: login05.o2.rc.hms.harvard.edu

Starting an interactive session.
srun: job 40261194 queued and waiting for resources
srun: job 40261194 has been allocated resources
Node: compute-a-17-95

Starting Jupyter notebook.
jupyter notebook --port=8887 --no-browser
Failed to launch jupyter. (timed out, 60)

Starting a second connection to the login node.
Connecting to the interactive node.

Jupyter is ready! Access at:
False
Opening in browser...
Traceback (most recent call last):
  File "/Users/davidd/anaconda/bin/jupyter-o2", line 11, in <module>
    sys.exit(main())
  File "/Users/davidd/anaconda/lib/python2.7/site-packages/jupyter_o2/jupyter_o2.py", line 649, in main
    jupyter_o2_runner.run()
  File "/Users/davidd/anaconda/lib/python2.7/site-packages/jupyter_o2/jupyter_o2.py", line 348, in run
    if self.connect() or self.keep_alive:
  File "/Users/davidd/anaconda/lib/python2.7/site-packages/jupyter_o2/jupyter_o2.py", line 420, in connect
    if not self.open_in_browser(jp_site):
  File "/Users/davidd/anaconda/lib/python2.7/site-packages/jupyter_o2/jupyter_o2.py", line 526, in open_in_browser
    webbrowser.open(site, new=2)
  File "/Users/davidd/anaconda/lib/python2.7/webbrowser.py", line 61, in open
    if browser.open(url, new, autoraise):
  File "/Users/davidd/anaconda/lib/python2.7/webbrowser.py", line 623, in open
    script = 'open location "%s"' % url.replace('"', '%22') # opens in default browser
AttributeError: 'bool' object has no attribute 'replace'

**Comment by aaronkollasch** [comment] 2019-05-09 08:20
Hi David,

Thanks for the report!

Looks like the initial error is at `Failed to launch jupyter. (timed out, 60)`, and jupyter-o2 should exit at that point. I'll make a quick fix so that the program doesn't continue beyond a (currently) unrecoverable error.

As for the cause of the error, either jupyter is taking too long to start on the server side (>60s, unlikely, but sometimes the file system can be slow), it's not printing the link to the web interface, or pexpect is not catching that link for some reason. Running jupyter-o2 in verbose mode (`jupyter-o2 -v`) will show the messages jupyter prints as it starts up, which should distinguish these scenarios.

**Comment by aaronkollasch** [comment] 2020-02-03 20:47
Closing this issue, but feel free to comment if it pops up again.

**Closed as completed by aaronkollasch** 2020-02-03 20:47 UTC
Labels: bug
